sonar.projectKey=avrut-WI264_grad_assessment_asava
sonar.organization=avrut-wi264

sonar.sources=.

sonar.sourceEncoding=UTF-8

sonar.java.binaries=backend/apigateway/target/classes,backend/auth-service/target/classes,backend/company-service/target/classes,backend/service-registry/target/classes


sonar.exclusions=**/node_modules/**,**/*.spec.ts