spring.application.name=portfolio-service


server.port=8084
# spring.datasource.url=jdbc:postgresql://localhost:5432/asava_trading
spring.datasource.url=jdbc:postgresql://localhost:5432/test
spring.datasource.username=postgres
# spring.datasource.password=hydroarchon
spring.datasource.password=123@Akash
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# 🔹 Disable Open Session in View (recommended)
spring.jpa.open-in-view=false

# 🔹 Eureka (VERY IMPORTANT for Feign)
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# 🔹 Optional: show SQL params (debugging)
spring.jpa.properties.hibernate.format_sql=true